export const Chips = {
    cannon: {
        id: 1,
        name: "Cannon",
        damage: 40,
        element: "Null",
        type: "Standard",
    },
    hicannon: {
        id: 2,
        name: "HiCannon",
        damage: 100,
        element: "Null",
        type: "Standard",
    },
    mcannon: {
        id: 3,
        name: "M-Cannon",
        damage: 180,
        element: "Null",
        type: "Standard",
    },
    airshot: {
        id: 4,
        name: "AirShot",
        damage: 20,
        element: "Wind",
        type: "Standard",
    },
    vulcan1: {
        id: 5,
        name: "Vulcan1",
        damage: {
            amount: 10,
            hits: 3
        },
        element: "Null",
        type: "Standard",
    },
    vulcan2: {
        id: 6,
        name: "Vulcan2",
        damage: {
            amount: 15,
            hits: 4
        },
        element: "Null",
        type: "Standard",
    },
    vulcan3: {
        id: 7,
        name: "Vulcan3",
        damage: {
            amount: 20,
            hits: 5
        },
        element: "Null",
        type: "Standard",
    },
    suprvulc: {
        id: 7,
        name: "SuprVulc",
        damage: {
            amount: 20,
            hits: 10
        },
        element: "Null",
        type: "Standard",
    },
    spreadr1: {
        id: 8,
        name: "Spreadr1",
        damage: 30,
        element: "Null",
        type: "Standard",
    },
    spreadr2: {
        id: 9,
        name: "Spreadr2",
        damage: 60,
        element: "Null",
        type: "Standard",
    },
    spreadr3: {
        id: 10,
        name: "Spreadr3",
        damage: 90,
        element: "Null",
        type: "Standard",
    },
    tankcan1: {
        id: 11,
        name: "TankCan1",
        damage: 120,
        element: "Null",
        type: "Standard",
    },
    tankcan2: {
        id: 12,
        name: "TankCan2",
        damage: 160,
        element: "Null",
        type: "Standard"
    },
    tankcan3: {
        id: 12,
        name: "TankCan3",
        damage: 200,
        element: "Null",
        type: "Standard"
    },
    gundels1: {
        id: 12,
        name: "GunDelS1",
        // TODO
        element: "Null",
        type: "Standard"
    },
    gundels2: {
        id: 12,
        name: "GunDelS2",
        // TODO
        element: "Null",
        type: "Standard"
    },
    gundels3: {
        id: 12,
        name: "GunDelS3",
        // TODO
        element: "Null",
        type: "Standard"
    },
    yoyo: {
        id: 12,
        name: "YoYo",
        damage: {
            amount: 50,
            hits: 3
        },
        element: "Null",
        type: "Standard"
    },
    firebrn1: {
        id: 12,
        name: "FireBrn1",
        damage: 70,
        element: "Fire",
        type: "Standard"
    },
    firebrn2: {
        id: 12,
        name: "FireBrn2",
        damage: 110,
        element: "Fire",
        type: "Standard"
    },
    firebrn3: {
        id: 21,
        name: "FireBrn3",
        damage: 150,
        element: "Fire",
        type: "Standard",
    },
    widesht: {
        id: 22,
        name: "WideSht",
        damage: 100,
        element: "Aqua",
        type: "Standard",
    },
    trnarrw1: {
        id: 23,
        name: "TrnArrw1",
        damage: 30,
        element: "Aqua",
        type: "Standard",
    },
    trnarrw2: {
        id: 24,
        name: "TrnArrw2",
        damage: 40,
        element: "Aqua",
        type: "Standard",
    },
    trnarrw3: {
        id: 25,
        name: "TrnArrw3",
        damage: 50,
        element: "Aqua",
        type: "Standard",
    },
    bblstar1: {
        id: 26,
        name: "BblStar1",
        damage: 60,
        element: "Aqua",
        type: "Standard",
    },
    bblstar2: {
        id: 27,
        name: "BblStar2",
        damage: 80,
        element: "Aqua",
        type: "Standard",
    },
    bblstar3: {
        id: 28,
        name: "BblStar3",
        damage: 100,
        element: "Aqua",
        type: "Standard",
    },
    thunder: {
        id: 29,
        name: "Thunder",
        damage: 40,
        element: "Elec",
        type: "Standard",
    },
    dolthdr1: {
        id: 30,
        name: "DolThdr1",
        damage: 120,
        element: "Elec",
        type: "Standard",
    },
    dolthdr2: {
        id: 31,
        name: "DolThdr2",
        damage: 150,
        element: "Elec",
        type: "Standard",
    },
    dolthdr3: {
        id: 32,
        name: "DolThdr3",
        damage: 180,
        element: "Elec",
        type: "Standard",
    },
    elcpuls1: {
        id: 33,
        name: "ElcPuls1",
        damage: 100,
        element: "Elec",
        type: "Standard",
    },
    elcpuls2: {
        id: 34,
        name: "ElcPuls2",
        damage: 120,
        element: "Elec",
        type: "Standard",
    },
    elcpuls3: {
        id: 35,
        name: "ElcPuls3",
        damage: 140,
        element: "Elec",
        type: "Standard",
    },
    cornsht1: {
        id: 36,
        name: "CornSht1",
        damage: 50,
        element: "Wood",
        type: "Standard",
    },
    cornsht2: {
        id: 37,
        name: "CornSht2",
        damage: 60,
        element: "Wood",
        type: "Standard",
    },
    cornsht3: {
        id: 38,
        name: "CornSht3",
        damage: 70,
        element: "Wood",
        type: "Standard",
    },
    rskyhny1: {
        id: 39,
        name: "RskyHny1",
        damage: 10,
        element: "Wood",
        type: "Standard",
    },
    rskyhny2: {
        id: 40,
        name: "RskyHny2",
        damage: 15,
        element: "Wood",
        type: "Standard",
    },
    rskyhny3: {
        id: 41,
        name: "RskyHny3",
        damage: 20,
        element: "Wood",
        type: "Standard",
    },
    rlnglog1: {
        id: 42,
        name: "RlngLog1",
        damage: 50,
        element: "Wood",
        type: "Standard",
    },
    rlnglog2: {
        id: 43,
        name: "RlngLog2",
        damage: 70,
        element: "Wood",
        type: "Standard",
    },
    rlnglog3: {
        id: 44,
        name: "RlngLog3",
        damage: 90,
        element: "Wood",
        type: "Standard",
    },
    ironshl1: {
        id: 45,
        name: "IronShl1",
        damage: 70,
        element: "Break",
        type: "Standard",
    },
    ironshl2: {
        id: 46,
        name: "IronShl2",
        damage: 100,
        element: "Break",
        type: "Standard",
    },
    ironshl3: {
        id: 47,
        name: "IronShl3",
        damage: 130,
        element: "Break",
        type: "Standard",
    },
    aurahed1: {
        id: 48,
        name: "AuraHed1",
        damage: 130,
        element: "Break",
        type: "Standard",
    },
    aurahed2: {
        id: 49,
        name: "AuraHed2",
        damage: 150,
        element: "Break",
        type: "Standard",
    },
    aurahed3: {
        id: 50,
        name: "AuraHed3",
        damage: 170,
        element: "Break",
        type: "Standard",
    },
    airhocky: {
        id: 51,
        name: "AirHocky",
        damage: 60,
        element: "Break",
        type: "Standard",
    },
    drilarm: {
        id: 52,
        name: "DrilArm",
        damage: 70,
        element: "Break",
        type: "Standard",
    },
    tornado: {
        id: 53,
        name: "Tornado",
        damage: 20,
        element: "Wind",
        type: "Standard",
    },
    static: {
        id: 54,
        name: "Static",
        damage: 20,
        element: "Wind",
        type: "Standard",
    },
    machgun1: {
        id: 55,
        name: "MachGun1",
        damage: 30,
        element: "Cursor",
        type: "Standard",
    },
    machgun2: {
        id: 56,
        name: "MachGun2",
        damage: 50,
        element: "Cursor",
        type: "Standard",
    },
    machgun3: {
        id: 57,
        name: "MachGun3",
        damage: 70,
        element: "Cursor",
        type: "Standard",
    },
    minibomb: {
        id: 58,
        name: "MiniBomb",
        damage: 50,
        element: "Null",
        type: "Standard",
    },
    bigbomb: {
        id: 59,
        name: "BigBomb",
        damage: 140,
        element: "Null",
        type: "Standard",
    },
    energbom: {
        id: 60,
        name: "EnergBom",
        damage: 40,
        element: "Null",
        type: "Standard",
    },
    megenbom: {
        id: 61,
        name: "MegEnBom",
        damage: 60,
        element: "Null",
        type: "Standard",
    },
    flshbom1: {
        id: 62,
        name: "FlshBom1",
        damage: 40,
        element: "Null",
        type: "Standard",
    },
    flshbom2: {
        id: 63,
        name: "FlshBom2",
        damage: 70,
        element: "Null",
        type: "Standard",
    },
    flshbom3: {
        id: 64,
        name: "FlshBom3",
        damage: 100,
        element: "Null",
        type: "Standard",
    },
    blkbomb: {
        id: 65,
        name: "BlkBomb",
        damage: 250,
        element: "Fire",
        type: "Standard",
    },
    bugbomb: {
        id: 66,
        name: "BugBomb",
        element: "Null",
        type: "Standard",
    },
    grasseed: {
        id: 67,
        name: "GrasSeed",
        damage: 10,
        element: "Wood",
        type: "Standard",
    },
    iceseed: {
        id: 68,
        name: "IceSeed",
        damage: 10,
        element: "Aqua",
        type: "Standard",
    },
    poisseed: {
        id: 69,
        name: "PoisSeed",
        damage: 10,
        element: "Null",
        type: "Standard",
    },
    sword: {
        id: 70,
        name: "Sword",
        damage: 80,
        element: "Sword",
        type: "Standard",
    },
    wideswrd: {
        id: 71,
        name: "WideSwrd",
        damage: 80,
        element: "Sword",
        type: "Standard",
    },
    longswrd: {
        id: 72,
        name: "LongSwrd",
        damage: 100,
        element: "Sword",
        type: "Standard",
    },
    wideblde: {
        id: 73,
        name: "WideBlde",
        damage: 150,
        element: "Sword",
        type: "Standard",
    },
    longblde: {
        id: 74,
        name: "LongBlde",
        damage: 150,
        element: "Sword",
        type: "Standard",
    },
    fireswrd: {
        id: 75,
        name: "FireSwrd",
        damage: 140,
        element: "Fire",
        type: "Standard",
    },
    aquaswrd: {
        id: 76,
        name: "AquaSwrd",
        damage: 160,
        element: "Aqua",
        type: "Standard",
    },
    elecswrd: {
        id: 77,
        name: "ElecSwrd",
        damage: 120,
        element: "Elec",
        type: "Standard",
    },
    bambswrd: {
        id: 78,
        name: "BambSwrd",
        damage: 150,
        element: "Wood",
        type: "Standard",
    },
    windrack: {
        id: 79,
        name: "WindRack",
        damage: 140,
        element: "Wind",
        type: "Standard",
    },
    stepswrd: {
        id: 80,
        name: "StepSwrd",
        damage: 160,
        element: "Sword",
        type: "Standard",
    },
    varswrd: {
        id: 81,
        name: "VarSwrd",
        damage: 160,
        element: "Sword",
        type: "Standard",
    },
    neovari: {
        id: 82,
        name: "NeoVari",
        damage: 220,
        element: "Sword",
        type: "Standard",
    },
    moonbld: {
        id: 83,
        name: "MoonBld",
        damage: 130,
        element: "Sword",
        type: "Standard",
    },
    muramasa: {
        id: 84,
        name: "Muramasa",
        element: "Sword",
        type: "Standard",
    },
    mchnswrd: {
        id: 85,
        name: "MchnSwrd",
        damage: 200,
        element: "Null",
        type: "Standard",
    },
    elemswrd: {
        id: 86,
        name: "ElemSwrd",
        damage: 220,
        element: "Null",
        type: "Standard",
    },
    assnswrd: {
        id: 87,
        name: "AssnSwrd",
        damage: 240,
        element: "Null",
        type: "Standard",
    },
    crakshot: {
        id: 88,
        name: "CrakShot",
        damage: 60,
        element: "Null",
        type: "Standard",
    },
    dublshot: {
        id: 89,
        name: "DublShot",
        damage: 60,
        element: "Null",
        type: "Standard",
    },
    trplshot: {
        id: 90,
        name: "TrplShot",
        damage: 100,
        element: "Null",
        type: "Standard",
    },
    rflectr1: {
        id: 91,
        name: "Rflectr1",
        damage: 60,
        element: "Null",
        type: "Standard",
    },
    rflectr2: {
        id: 92,
        name: "Rflectr2",
        damage: 120,
        element: "Null",
        type: "Standard",
    },
    rflectr3: {
        id: 93,
        name: "Rflectr3",
        damage: 200,
        element: "Null",
        type: "Standard",
    },
    wavearm1: {
        id: 94,
        name: "WaveArm1",
        damage: 80,
        element: "Null",
        type: "Standard",
    },
    wavearm2: {
        id: 95,
        name: "WaveArm2",
        damage: 120,
        element: "Null",
        type: "Standard",
    },
    wavearm3: {
        id: 96,
        name: "WaveArm3",
        damage: 160,
        element: "Null",
        type: "Standard",
    },
    sandwrm1: {
        id: 97,
        name: "SandWrm1",
        damage: 130,
        element: "Null",
        type: "Standard",
    },
    sandwrm2: {
        id: 98,
        name: "SandWrm2",
        damage: 150,
        element: "Null",
        type: "Standard",
    },
    sandwrm3: {
        id: 99,
        name: "SandWrm3",
        damage: 170,
        element: "Null",
        type: "Standard",
    },
    sumnblk1: {
        id: 100,
        name: "SumnBlk1",
        damage: 160,
        element: "Null",
        type: "Standard",
    },
    sumnblk2: {
        id: 101,
        name: "SumnBlk2",
        damage: 200,
        element: "Null",
        type: "Standard",
    },
    sumnblk3: {
        id: 102,
        name: "SumnBlk3",
        damage: 260,
        element: "Null",
        type: "Standard",
    },
    snake: {
        id: 103,
        name: "Snake",
        damage: 30,
        element: "Null",
        type: "Standard",
    },
    numbrbl: {
        id: 104,
        name: "NumbrBl",
        element: "Null",
        type: "Standard",
    },
    firehit1: {
        id: 105,
        name: "FireHit1",
        damage: 60,
        element: "Fire",
        type: "Standard",
    },
    firehit2: {
        id: 106,
        name: "FireHit2",
        damage: 120,
        element: "Fire",
        type: "Standard",
    },
    firehit3: {
        id: 107,
        name: "FireHit3",
        damage: 180,
        element: "Fire",
        type: "Standard",
    },
    burnsqr1: {
        id: 108,
        name: "BurnSqr1",
        damage: 100,
        element: "Fire",
        type: "Standard",
    },
    burnsqr2: {
        id: 109,
        name: "BurnSqr2",
        damage: 120,
        element: "Fire",
        type: "Standard",
    },
    burnsqr3: {
        id: 110,
        name: "BurnSqr3",
        damage: 140,
        element: "Fire",
        type: "Standard",
    },
    meteors: {
        id: 111,
        name: "Meteors",
        damage: 40,
        element: "Fire",
        type: "Standard",
    },
    aquandl1: {
        id: 112,
        name: "AquaNdl1",
        damage: 40,
        element: "Aqua",
        type: "Standard",
    },
    aquandl2: {
        id: 113,
        name: "AquaNdl2",
        damage: 60,
        element: "Aqua",
        type: "Standard",
    },
    aquandl3: {
        id: 114,
        name: "AquaNdl3",
        damage: 80,
        element: "Aqua",
        type: "Standard",
    },
    blzrdbal: {
        id: 115,
        name: "BlzrdBal",
        damage: 150,
        element: "Aqua",
        type: "Standard",
    },
    sensor1: {
        id: 116,
        name: "Sensor1",
        damage: 100,
        element: "Elec",
        type: "Standard",
    },
    sensor2: {
        id: 117,
        name: "Sensor2",
        damage: 130,
        element: "Elec",
        type: "Standard",
    },
    sensor3: {
        id: 118,
        name: "Sensor3",
        damage: 160,
        element: "Elec",
        type: "Standard",
    },
    boomer: {
        id: 119,
        name: "Boomer",
        damage: 100,
        element: "Wood",
        type: "Standard",
    },
    hiboomer: {
        id: 120,
        name: "HiBoomer",
        damage: 140,
        element: "Wood",
        type: "Standard",
    },
    mboomer: {
        id: 121,
        name: "M-Boomer",
        damage: 170,
        element: "Wood",
        type: "Standard",
    },
    lance: {
        id: 122,
        name: "Lance",
        damage: 150,
        element: "Wood",
        type: "Standard",
    },
    heatdrgn: {
        id: 123,
        name: "HeatDrgn",
        damage: 140,
        element: "Fire",
        type: "Standard",
    },
    elecdrgn: {
        id: 124,
        name: "ElecDrgn",
        damage: 150,
        element: "Elec",
        type: "Standard",
    },
    aquadrgn: {
        id: 125,
        name: "AquaDrgn",
        damage: 120,
        element: "Aqua",
        type: "Standard",
    },
    wooddrgn: {
        id: 126,
        name: "WoodDrgn",
        damage: 130,
        element: "Wood",
        type: "Standard",
    },
    golmhit1: {
        id: 127,
        name: "GolmHit1",
        damage: 140,
        element: "Break",
        type: "Standard",
    },
    golmhit2: {
        id: 128,
        name: "GolmHit2",
        damage: 190,
        element: "Break",
        type: "Standard",
    },
    golmhit3: {
        id: 129,
        name: "GolmHit3",
        damage: 250,
        element: "Break",
        type: "Standard",
    },
    justcone: {
        id: 130,
        name: "JustcOne",
        damage: 220,
        element: "Break",
        type: "Standard",
    },
    airspin1: {
        id: 131,
        name: "AirSpin1",
        damage: 50,
        element: "Wind",
        type: "Standard",
    },
    airspin2: {
        id: 132,
        name: "AirSpin2",
        damage: 50,
        element: "Wind",
        type: "Standard",
    },
    airspin3: {
        id: 133,
        name: "AirSpin3",
        damage: 50,
        element: "Wind",
        type: "Standard",
    },
    wind: {
        id: 134,
        name: "Wind",
        element: "Wind",
        type: "Standard",
    },
    fan: {
        id: 135,
        name: "Fan",
        element: "Wind",
        type: "Standard",
    },
    magnum: {
        id: 136,
        name: "Magnum",
        damage: 130,
        element: "Cursor",
        type: "Standard",
    },
    circgun: {
        id: 137,
        name: "CircGun",
        damage: 150,
        element: "Cursor",
        type: "Standard",
    },
    rockcube: {
        id: 138,
        name: "RockCube",
        damage: 200,
        element: "Obstacle",
        type: "Standard",
    },
    lilbolr1: {
        id: 139,
        name: "LilBolr1",
        damage: 100,
        element: "Obstacle",
        type: "Standard",
    },
    lilbolr2: {
        id: 140,
        name: "LilBolr2",
        damage: 140,
        element: "Obstacle",
        type: "Standard",
    },
    lilbolr3: {
        id: 141,
        name: "LilBolr3",
        damage: 180,
        element: "Obstacle",
        type: "Standard",
    },
    airraid1: {
        id: 142,
        name: "AirRaid1",
        damage: 10,
        element: "Obstacle",
        type: "Standard",
    },
    airraid2: {
        id: 143,
        name: "AirRaid2",
        damage: 10,
        element: "Obstacle",
        type: "Standard",
    },
    airraid3: {
        id: 144,
        name: "AirRaid3",
        damage: 10,
        element: "Obstacle",
        type: "Standard",
    },
    timebom1: {
        id: 145,
        name: "TimeBom1",
        damage: 150,
        element: "Obstacle",
        type: "Standard",
    },
    timebom2: {
        id: 146,
        name: "TimeBom2",
        damage: 190,
        element: "Obstacle",
        type: "Standard",
    },
    timebom3: {
        id: 147,
        name: "TimeBom3",
        damage: 230,
        element: "Obstacle",
        type: "Standard",
    },
    mine: {
        id: 148,
        name: "Mine",
        damage: 200,
        element: "Obstacle",
        type: "Standard",
    },
    fanfare: {
        id: 149,
        name: "Fanfare",
        element: "Obstacle",
        type: "Standard",
    },
    discord: {
        id: 150,
        name: "Discord",
        element: "Obstacle",
        type: "Standard",
    },
    timpani: {
        id: 151,
        name: "Timpani",
        element: "Obstacle",
        type: "Standard",
    },
    silence: {
        id: 152,
        name: "Silence",
        element: "Obstacle",
        type: "Standard",
    },
    vdoll: {
        id: 153,
        name: "VDoll",
        damage: 10,
        element: "Obstacle",
        type: "Standard",
    },
    guardian: {
        id: 154,
        name: "Guardian",
        damage: 200,
        element: "Obstacle",
        type: "Standard",
    },
    anubis: {
        id: 155,
        name: "Anubis",
        damage: 1,
        element: "Obstacle",
        type: "Standard",
    },
    recov10: {
        id: 156,
        name: "Recov10",
        element: "Null",
        type: "Standard",
    },
    recov30: {
        id: 157,
        name: "Recov30",
        element: "Null",
        type: "Standard",
    },
    recov50: {
        id: 158,
        name: "Recov50",
        element: "Null",
        type: "Standard",
    },
    recov80: {
        id: 159,
        name: "Recov80",
        element: "Null",
        type: "Standard",
    },
    recov120: {
        id: 160,
        name: "Recov120",
        element: "Null",
        type: "Standard",
    },
    recov150: {
        id: 161,
        name: "Recov150",
        element: "Null",
        type: "Standard",
    },
    recov200: {
        id: 162,
        name: "Recov200",
        element: "Null",
        type: "Standard",
    },
    recov300: {
        id: 163,
        name: "Recov300",
        element: "Null",
        type: "Standard",
    },
    panlgrab: {
        id: 164,
        name: "PanlGrab",
        damage: 10,
        element: "Null",
        type: "Standard",
    },
    areagrab: {
        id: 165,
        name: "AreaGrab",
        damage: 10,
        element: "Null",
        type: "Standard",
    },
    grabbnsh: {
        id: 166,
        name: "GrabBnsh",
        damage: 20,
        element: "Null",
        type: "Standard",
    },
    grabrvng: {
        id: 167,
        name: "GrabRvng",
        damage: 40,
        element: "Null",
        type: "Standard",
    },
    pnlretrn: {
        id: 168,
        name: "PnlRetrn",
        element: "Null",
        type: "Standard",
    },
    geddon: {
        id: 169,
        name: "Geddon",
        element: "Null",
        type: "Standard",
    },
    holypanl: {
        id: 170,
        name: "HolyPanl",
        element: "Null",
        type: "Standard",
    },
    snctuary: {
        id: 171,
        name: "Snctuary",
        element: "Null",
        type: "Standard",
    },
    comingrd: {
        id: 172,
        name: "ComingRd",
        damage: 40,
        element: "Null",
        type: "Standard",
    },
    goingrd: {
        id: 173,
        name: "GoingRd",
        damage: 40,
        element: "Null",
        type: "Standard",
    },
    slogauge: {
        id: 174,
        name: "SloGauge",
        element: "Null",
        type: "Standard",
    },
    fstgauge: {
        id: 175,
        name: "FstGauge",
        element: "Null",
        type: "Standard",
    },
    fullcust: {
        id: 176,
        name: "FullCust",
        element: "Null",
        type: "Standard",
    },
    busterup: {
        id: 177,
        name: "BusterUp",
        element: "Plus",
        type: "Standard",
    },
    bugfix: {
        id: 178,
        name: "BugFix",
        element: "Null",
        type: "Standard",
    },
    invisibl: {
        id: 179,
        name: "Invisibl",
        element: "Null",
        type: "Standard",
    },
    barrier: {
        id: 180,
        name: "Barrier",
        element: "Null",
        type: "Standard",
    },
    barr100: {
        id: 181,
        name: "Barr100",
        element: "Null",
        type: "Standard",
    },
    barr200: {
        id: 182,
        name: "Barr200",
        element: "Null",
        type: "Standard",
    },
    bblwrap: {
        id: 183,
        name: "BblWrap",
        element: "Aqua",
        type: "Standard",
    },
    lifeaur: {
        id: 184,
        name: "LifeAur",
        element: "Null",
        type: "Standard",
    },
    magcoil: {
        id: 185,
        name: "MagCoil",
        element: "Null",
        type: "Standard",
    },
    colarmy: {
        id: 186,
        name: "ColArmy",
        damage: 40,
        element: "Null",
        type: "Standard",
    },
    elemtrap: {
        id: 187,
        name: "ElemTrap",
        damage: 240,
        element: "Null",
        type: "Standard",
    },
    antinavi: {
        id: 188,
        name: "AntiNavi",
        element: "Null",
        type: "Standard",
    },
    antidmg: {
        id: 189,
        name: "AntiDmg",
        damage: 100,
        element: "Null",
        type: "Standard",
    },
    antiswrd: {
        id: 190,
        name: "AntiSwrd",
        damage: 100,
        element: "Sword",
        type: "Standard",
    },
    antirecv: {
        id: 191,
        name: "AntiRecv",
        element: "Null",
        type: "Standard",
    },
    whicapsl: {
        id: 192,
        name: "WhiCapsl",
        element: "Null",
        type: "Standard",
    },
    uninstll: {
        id: 193,
        name: "Uninstll",
        element: "Null",
        type: "Standard",
    },
    copydmg: {
        id: 194,
        name: "CopyDmg",
        element: "Cursor",
        type: "Standard",
    },
    lifesync: {
        id: 195,
        name: "LifeSync",
        element: "Cursor",
        type: "Standard",
    },
    atk10: {
        id: 196,
        name: "Atk+10",
        damage: 10,
        element: "Plus",
        type: "Standard",
    },
    atk30: {
        id: 197,
        name: "Atk+30",
        damage: 30,
        element: "Plus",
        type: "Standard",
    },
    navi20: {
        id: 198,
        name: "Navi+20",
        damage: 20,
        element: "Plus",
        type: "Standard",
    },
    colorpt: {
        id: 199,
        name: "ColorPt",
        element: "Plus",
        type: "Standard",
    },
    dblpoint: {
        id: 200,
        name: "DblPoint",
        element: "Plus",
        type: "Standard",
    },
    //Mega
    roll: {
        id: 201,
        name: "Roll",
        damage: 20,
        element: "Null",
        type: "Mega"
    },
    roll2: {
        id: 202,
        name: "Roll2",
        damage: 40,
        element: "Null",
        type: "Mega"
    },
    roll3: {
        id: 203,
        name: "Roll3",
        damage: 60,
        element: "Null",
        type: "Mega"
    },
    protoman: {
        id: 204,
        name: "ProtoMan",
        damage: 150,
        element: "Sword",
        type: "Mega"
    },
    protomnex: {
        id: 205,
        name: "ProtoMnEX",
        damage: 170,
        element: "Sword",
        type: "Mega"
    },
    protomnsp: {
        id: 206,
        name: "ProtoMnSP",
        damage: 290,
        element: "Sword",
        type: "Mega"
    },
    aquaman: {
        id: 207,
        name: "AquaMan",
        damage: 50,
        element: "Aqua",
        type: "Mega"
    },
    aquamanex: {
        id: 208,
        name: "AquaManEX",
        damage: 60,
        element: "Aqua",
        type: "Mega"
    },
    aquamansp: {
        id: 209,
        name: "AquaManSP",
        damage: 120,
        element: "Aqua",
        type: "Mega"
    },
    tmhkman: {
        id: 210,
        name: "TmhkMan",
        damage: 140,
        element: "Wood",
        type: "Mega"
    },
    tmhkmanex: {
        id: 211,
        name: "TmhkManEX",
        damage: 160,
        element: "Wood",
        type: "Mega"
    },
    tmhkmansp: {
        id: 212,
        name: "TmhkManSP",
        damage: 280,
        element: "Wood",
        type: "Mega"
    },
    tenguman: {
        id: 213,
        name: "TenguMan",
        damage: 70,
        element: "Wind",
        type: "Mega"
    },
    tengumnex: {
        id: 214,
        name: "TenguMnEX",
        damage: 90,
        element: "Wind",
        type: "Mega"
    },
    tengumnsp: {
        id: 215,
        name: "TenguMnSP",
        damage: 160,
        element: "Wind",
        type: "Mega"
    },
    grndman: {
        id: 216,
        name: "GrndMan",
        damage: 60,
        element: "Break",
        type: "Mega"
    },
    grndmanex: {
        id: 217,
        name: "GrndManEX",
        damage: 70,
        element: "Break",
        type: "Mega"
    },
    grndmansp: {
        id: 218,
        name: "GrndManSP",
        damage: 130,
        element: "Break",
        type: "Mega"
    },
    dustman: {
        id: 219,
        name: "DustMan",
        damage: 110,
        element: "Null",
        type: "Mega"
    },
    dustmanex: {
        id: 220,
        name: "DustManEX",
        damage: 130,
        element: "Null",
        type: "Mega"
    },
    dustmansp: {
        id: 221,
        name: "DustManSP",
        damage: 200,
        element: "Null",
        type: "Mega"
    },
    heatman: {
        id: 222,
        name: "HeatMan",
        damage: 100,
        element: "Fire",
        type: "Mega"
    },
    heatmanex: {
        id: 223,
        name: "HeatManEX",
        damage: 130,
        element: "Fire",
        type: "Mega"
    },
    heatmansp: {
        id: 224,
        name: "HeatManSP",
        damage: 260,
        element: "Fire",
        type: "Mega"
    },
    elecman: {
        id: 225,
        name: "ElecMan",
        damage: 120,
        element: "Elec",
        type: "Mega"
    },
    elecmanex: {
        id: 226,
        name: "ElecManEX",
        damage: 140,
        element: "Elec",
        type: "Mega"
    },
    elecmansp: {
        id: 227,
        name: "ElecManSP",
        damage: 210,
        element: "Elec",
        type: "Mega"
    },
    slashman: {
        id: 228,
        name: "SlashMan",
        damage: 80,
        element: "Sword",
        type: "Mega"
    },
    slashmnex: {
        id: 229,
        name: "SlashMnEX",
        damage: 100,
        element: "Sword",
        type: "Mega"
    },
    slashmnsp: {
        id: 230,
        name: "SlashMnSP",
        damage: 220,
        element: "Sword",
        type: "Mega"
    },
    eraseman: {
        id: 231,
        name: "EraseMan",
        damage: 120,
        element: "Cursor",
        type: "Mega",
    },
    erasemnex: {
        id: 232,
        name: "EraseMnEX",
        damage: 140,
        element: "Cursor",
        type: "Mega",
    },
    erasemnsp: {
        id: 233,
        name: "EraseMnSP",
        damage: 210,
        element: "Cursor",
        type: "Mega",
    },
    chrgeman: {
        id: 234,
        name: "ChrgeMan",
        damage: 60,
        element: "Null",
        type: "Mega"
    },
    chrgemnex: {
        id: 235,
        name: "ChrgeMnEX",
        damage: 70,
        element: "Null",
        type: "Mega"
    },
    chrgemnsp: {
        id: 236,
        name: "ChrgeMnSP",
        damage: 130,
        element: "Null",
        type: "Mega"
    },
    blastman: {
        id: 237,
        name: "BlastMan",
        damage: 120,
        element: "Fire",
        type: "Mega"
    },
    blastmnex: {
        id: 238,
        name: "BlastMnEX",
        damage: 140,
        element: "Fire",
        type: "Mega"
    },
    blastmnsp: {
        id: 239,
        name: "BlastMnSP",
        damage: 250,
        element: "Fire",
        type: "Mega"
    },
    diveman: {
        id: 240,
        name: "DiveMan",
        damage: 130,
        element: "Aqua",
        type: "Mega"
    },
    divemanex: {
        id: 241,
        name: "DiveManEX",
        damage: 150,
        element: "Aqua",
        type: "Mega"
    },
    divemansp: {
        id: 242,
        name: "DiveManSP",
        damage: 270,
        element: "Aqua",
        type: "Mega"
    },
    crcusman: {
        id: 243,
        name: "CrcusMan",
        damage: 20,
        element: "Null",
        type: "Mega"
    },
    crcusmnex: {
        id: 244,
        name: "CrcusMnEX",
        damage: 25,
        element: "Null",
        type: "Mega"
    },
    crcusmnsp: {
        id: 245,
        name: "CrcusMnSP",
        damage: 55,
        element: "Null",
        type: "Mega"
    },
    judgeman: {
        id: 246,
        name: "JudgeMan",
        damage: 100,
        element: "Elec",
        type: "Mega"
    },
    judgemnex: {
        id: 247,
        name: "JudgeMnEX",
        damage: 120,
        element: "Elec",
        type: "Mega"
    },
    judgemnsp: {
        id: 248,
        name: "JudgeMnSP",
        damage: 190,
        element: "Elec",
        type: "Mega"
    },
    elmntman: {
        id: 249,
        name: "ElmntMan",
        damage: 100,
        element: "Null",
        type: "Mega"
    },
    elmntmnex: {
        id: 250,
        name: "ElmntMnEX",
        damage: 120,
        element: "Null",
        type: "Mega"
    },
    elmntmnsp: {
        id: 251,
        name: "ElmntMnSP",
        damage: 240,
        element: "Null",
        type: "Mega"
    },
    colonel: {
        id: 252,
        name: "Colonel",
        damage: 160,
        element: "Sword",
        type: "Mega"
    },
    colonelex: {
        id: 253,
        name: "ColonelEX",
        damage: 180,
        element: "Sword",
        type: "Mega"
    },
    colonelsp: {
        id: 254,
        name: "ColonelSP",
        damage: 300,
        element: "Sword",
        type: "Mega"
    },
    // Giga
    bass: {
        id: 255,
        name: "Bass",
        damage: 60,
        element: "Null",
        type: "Giga"
    },
    bighook: {
        id: 256,
        name: "BigHook",
        damage: 240,
        element: "Break",
        type: "Giga"
    },
    deltaray: {
        id: 257,
        name: "DeltaRay",
        damage: 260,
        element: "Sword",
        type: "Giga"
    },
    colforce: {
        id: 258,
        name: "ColForce",
        damage: 30,
        element: "Null",
        type: "Giga"
    },
    bugrswrd: {
        id: 259,
        name: "BugRSwrd",
        element: "Sword",
        type: "Giga"
    },
    bassanly: {
        id: 260,
        name: "BassAnly",
        damage: 160,
        element: "Null",
        type: "Giga"
    },
    metrknuk: {
        id: 261,
        name: "MetrKnuk",
        damage: 100,
        element: "Break",
        type: "Giga"
    },
    crossdiv: {
        id: 262,
        name: "CrossDiv",
        damage: 250,
        element: "Sword",
        type: "Giga"
    },
    hubbatc: {
        id: 263,
        name: "HubBatc",
        element: "Null",
        type: "Giga"
    },
    bgdththd: {
        id: 264,
        name: "BgDthThd",
        element: "Elec",
        type: "Giga"
    },
};
//# sourceMappingURL=chips.js.map